// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.11.0.0")]
[assembly: AssemblyFileVersionAttribute("1.11.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.11.0.0")]

